<?php include "01_dbcon.php"; ?>
<?php include "02_header.php"; ?>
<?php include "03_menu.php"; ?>
<?php

$options_stks="";
$sql = "SELECT * FROM smartdb.sm13_stk WHERE stk_include=1 ORDER BY stk_name";
// echo $sql;
$result2 = $con->query($sql);
if ($result2->num_rows > 0) {
  while($row2 = $result2->fetch_assoc()) {
    $stkm_id  	= $row2["stkm_id"];
    $stk_id  	= $row2["stk_id"];
    $stk_name  	= $row2["stk_name"];

	$options_stks .= "<option value='".$stkm_id."'>STK#".$stk_id.": ".$stk_name."</option>";
}}

$row_firstfound = "";

$sql = "SELECT * FROM smartdb.sm15_rc WHERE rc_section='FF' ORDER BY res_reason_code";
// echo $sql;
$result = $con->query($sql);
if ($result->num_rows > 0) {
  while($row = $result->fetch_assoc()) {
    $list_res_reason_code 	= $row['res_reason_code'];
    $list_rc_desc 			= $row['rc_desc'];
    $rc_long_desc 			= $row['rc_long_desc'];
    $rc_examples 			= $row['rc_examples'];
    $list_rc_desc = str_replace("Asset First Found - ", "", $list_rc_desc);
	$row_firstfound .= "<tr><td><button type='submit' name='res_reason_code' value='$list_res_reason_code' class='btn btn-primary'>$list_res_reason_code</button></td><td width='95%' align='center' style='padding-bottom:0px'><h5 class='card-title' style='margin-bottom:0px'>$list_rc_desc&nbsp;<small class='card-subtitle mb-2 text-muted'>$rc_long_desc. $rc_examples</small></h5></td><td align='right'><button type='submit' name='res_reason_code' value='$list_res_reason_code' class='btn btn-primary float-right'>$list_res_reason_code</button></td></tr>";
}}







?>











<br><br>
<form method="post" action="05_action.php">
	<input type="hidden" name="act" value="save_newfirstfound">

	<div class="container-fluid">
		<div class="row">
		    <div class="col-1"></div>
		    <div class="col-4">
		    	<h2>Create a first found</h2>
	    	</div>
		    <div class="col-6">
		    	<p>An item is classified as a first found if there appears to be no formal record of it in either the stocktake data, or the raw remainder data.You will first need to provide some additional preliminary information about the asset, before filling in the normal information.</p>
		    </div>
		    <div class="col-1"></div>
		</div>
		<div class="row">
		    <div class="col-1"></div>
		    <div class="col-lg">
		    	<b>1. Which stocktake and site does this first found belong to? (Stocktake must be active and included)</b>
		    	<select class="form-control" name="stkm_id">
		    		<?=$options_stks?>
		    	</select>
		    </div>
		    <div class="col-1"></div>
		</div>
		<div class="row">
		    <div class="col-1"></div>
		    <div class="col-lg">
		    	<b>2. Which standard asset description would you like to use?</b>
		    	<select class="form-control" name="asset_template">
					<option value=''></option>
					<option value='Z0001 ELECTRICAL RETICULATION'>Z0001 - ELECTRICAL RETICULATION</option>
					<option value='Z0002 SEWER RETICULATION'>Z0002 - SEWER RETICULATION</option>
					<option value='Z0003 FRESHWATER RETICULATION'>Z0003 - FRESHWATER RETICULATION</option>
					<option value='Z0004 NATURAL GAS RETICULATION'>Z0004 - NATURAL GAS RETICULATION</option>
					<option value='Z0005 BOTTLED GAS RETICULATION'>Z0005 - BOTTLED GAS RETICULATION</option>
					<option value='Z0006 FUEL OIL PIPING SYSTEM '>Z0006 - FUEL OIL PIPING SYSTEM </option>
					<option value='Z0007 STORM WATER DRAINS'>Z0007 - STORM WATER DRAINS</option>
					<option value='Z0008 IRRIGATION SYSTEMS EFFLUENT'>Z0008 - IRRIGATION SYSTEMS EFFLUENT</option>
					<option value='Z0009 IRRIGATION SYSTEMS WATER'>Z0009 - IRRIGATION SYSTEMS WATER</option>
					<option value='Z0010 STREET AND SECURITY LIGHTING'>Z0010 - STREET AND SECURITY LIGHTING</option>
					<option value='Z0011 CONTROL CABLE RETICULATION '>Z0011 - CONTROL CABLE RETICULATION </option>
					<option value='Z0012 AREA NETWORK AND TELEPHONE CABLING'>Z0012 - AREA NETWORK AND TELEPHONE CABLING</option>
					<option value='Z0013 SECURITY SERVICES'>Z0013 - SECURITY SERVICES</option>
					<option value='Z0014 FIRE SERVICES'>Z0014 - FIRE SERVICES</option>
					<option value='Z0015 AIRCRAFT HARDSTANDS'>Z0015 - AIRCRAFT HARDSTANDS</option>
					<option value='Z0016 AIRFIELD LIGHTING SYSTEM '>Z0016 - AIRFIELD LIGHTING SYSTEM </option>
					<option value='Z0017 RUNWAY AND TAXIWAYS'>Z0017 - RUNWAY AND TAXIWAYS</option>
					<option value='Z0018 AIRCRAFT EARTHING POINTS '>Z0018 - AIRCRAFT EARTHING POINTS </option>
					<option value='Z0019 ROADS'>Z0019 - ROADS</option>
					<option value='Z0020 FOOTPATHS/DRIVEWAYS/CYCLE TRACKS'>Z0020 - FOOTPATHS/DRIVEWAYS/CYCLE TRACKS</option>
					<option value='Z0021 LANDSCAPING/GROUNDS/PLAYING FIELDS & SPORT GROUNDS'>Z0021 - LANDSCAPING/GROUNDS/PLAYING FIELDS & SPORT GROUNDS</option>
					<option value='Z0022 PERIMETER AND INTERNAL FENCES/GATE'>Z0022 - PERIMETER AND INTERNAL FENCES/GATE</option>
					<option value='Z0023 RAILWAY LINES'>Z0023 - RAILWAY LINES</option>
					<option value='Z0026 STREET LIGHTING MARRIED QUARTERS'>Z0026 - STREET LIGHTING MARRIED QUARTERS</option>
					<option value='Z0027 ROAD SYSTEM MARRIED QUARTERS'>Z0027 - ROAD SYSTEM MARRIED QUARTERS</option>
					<option value='Z0028 BRIDGES/CAUSEWAYS/BREAKWATER/RETAINING WALLS & REVETMENTS'>Z0028 - BRIDGES/CAUSEWAYS/BREAKWATER/RETAINING WALLS & REVETMENTS</option>
					<option value='Z0029 CAR PARKS/ PARADE GROUNDS/HARDSTANDS'>Z0029 - CAR PARKS/ PARADE GROUNDS/HARDSTANDS</option>
					<option value='Z0030 TRADE WASTE PUMPING SYSTEMS '>Z0030 - TRADE WASTE PUMPING SYSTEMS </option>
					<option value='Z0031 CHANNELS AND DREDGING'>Z0031 - CHANNELS AND DREDGING</option>
					<option value='Z0032 DAMS AND PERMANENT WATER STORAGE FACILITIES (NOT TANKS)'>Z0032 - DAMS AND PERMANENT WATER STORAGE FACILITIES (NOT TANKS)</option>
					<option value='Z0033 SIGNAGE (ALL BASE SIGNAGE)'>Z0033 - SIGNAGE (ALL BASE SIGNAGE)</option>
					<option value='Z0034 FLAG POLES AND MONUMENTS/MEMORIAL ROCKS'>Z0034 - FLAG POLES AND MONUMENTS/MEMORIAL ROCKS</option>
					<option value='Z0051 NON-POTABLE WATER RETICULATION'>Z0051 - NON-POTABLE WATER RETICULATION</option>
					<option value='ADMIN AUDIO VISUAL-SYSTEM'>ADMIN - AUDIO VISUAL-SYSTEM</option>
					<option value='ADMIN AUDIO VISUAL-CAMERA-DIGITAL'>ADMIN - AUDIO VISUAL-CAMERA-DIGITAL</option>
					<option value='ADMIN AUDIO VISUAL-CAMERA-POLAROID'>ADMIN - AUDIO VISUAL-CAMERA-POLAROID</option>
					<option value='ADMIN AUDIO VISUAL-CAMERA-STILL'>ADMIN - AUDIO VISUAL-CAMERA-STILL</option>
					<option value='ADMIN AUDIO VISUAL-CAMERA-VIDEO'>ADMIN - AUDIO VISUAL-CAMERA-VIDEO</option>
					<option value='ADMIN AUDIO VISUAL-CAMERA-WEB'>ADMIN - AUDIO VISUAL-CAMERA-WEB</option>
					<option value='ADMIN AUDIO VISUAL-DIGITAL IMAGE PROJECTOR'>ADMIN - AUDIO VISUAL-DIGITAL IMAGE PROJECTOR</option>
					<option value='ADMIN AUDIO VISUAL-PHOTOGRAHIC PRESENTATION STAND'>ADMIN - AUDIO VISUAL-PHOTOGRAHIC PRESENTATION STAND</option>
					<option value='ADMIN AUDIO VISUAL-PHOTOGRAHIC PROJECTION UNIT'>ADMIN - AUDIO VISUAL-PHOTOGRAHIC PROJECTION UNIT</option>
					<option value='ADMIN AUDIO VISUAL-PLASMA SCREEN'>ADMIN - AUDIO VISUAL-PLASMA SCREEN</option>
					<option value='ADMIN AUDIO VISUAL-PROJECTOR-LCD LITEPRO'>ADMIN - AUDIO VISUAL-PROJECTOR-LCD LITEPRO</option>
					<option value='ADMIN AUDIO VISUAL-PROJECTOR-OVERHEAD'>ADMIN - AUDIO VISUAL-PROJECTOR-OVERHEAD</option>
					<option value='ADMIN AUDIO VISUAL-PROJECTOR-SLIDE'>ADMIN - AUDIO VISUAL-PROJECTOR-SLIDE</option>
					<option value='ADMIN AUDIO VISUAL-SLIDE CAROUSEL'>ADMIN - AUDIO VISUAL-SLIDE CAROUSEL</option>
					<option value='ADMIN AUDIO VISUAL-STEREO-PORTABLE'>ADMIN - AUDIO VISUAL-STEREO-PORTABLE</option>
					<option value='ADMIN AUDIO VISUAL-VIDEO CONFERENCE SYSTEM'>ADMIN - AUDIO VISUAL-VIDEO CONFERENCE SYSTEM</option>
					<option value='ADMIN BED-BUNK'>ADMIN - BED-BUNK</option>
					<option value='ADMIN BED-DOUBLE'>ADMIN - BED-DOUBLE</option>
					<option value='ADMIN BED-SINGLE'>ADMIN - BED-SINGLE</option>
					<option value='ADMIN BED-MATTRESS'>ADMIN - BED-MATTRESS</option>
					<option value='ADMIN BIKE-HAND'>ADMIN - BIKE-HAND</option>
					<option value='ADMIN BIKE-ELECTRIC'>ADMIN - BIKE-ELECTRIC</option>
					<option value='ADMIN BIKE-GOLF BUGGIE'>ADMIN - BIKE-GOLF BUGGIE</option>
					<option value='ADMIN BIKE-MOTOR BIKE'>ADMIN - BIKE-MOTOR BIKE</option>
					<option value='ADMIN BIKE-MOTOR SCOOTER'>ADMIN - BIKE-MOTOR SCOOTER</option>
					<option value='ADMIN BIKE-QUAD'>ADMIN - BIKE-QUAD</option>
					<option value='ADMIN BIKE-TRIKE'>ADMIN - BIKE-TRIKE</option>
					<option value='ADMIN BOATING EQUIPMENT-BUOYS'>ADMIN - BOATING EQUIPMENT-BUOYS</option>
					<option value='ADMIN BOATING EQUIPMENT-CANOE'>ADMIN - BOATING EQUIPMENT-CANOE</option>
					<option value='ADMIN BOATING EQUIPMENT-KAYAK'>ADMIN - BOATING EQUIPMENT-KAYAK</option>
					<option value='ADMIN BOATING EQUIPMENT-MOORINGS'>ADMIN - BOATING EQUIPMENT-MOORINGS</option>
					<option value='ADMIN BOATING EQUIPMENT-OIL SPILLAGE PONTOON'>ADMIN - BOATING EQUIPMENT-OIL SPILLAGE PONTOON</option>
					<option value='ADMIN BOATING EQUIPMENT-SAILING CRAFT-INFLATABLE'>ADMIN - BOATING EQUIPMENT-SAILING CRAFT-INFLATABLE</option>
					<option value='ADMIN BOATING EQUIPMENT-SAILING CRAFT-SMALL'>ADMIN - BOATING EQUIPMENT-SAILING CRAFT-SMALL</option>
					<option value='ADMIN BOATING EQUIPMENT-SAILS'>ADMIN - BOATING EQUIPMENT-SAILS</option>
					<option value='ADMIN BOATING EQUIPMENT-SPILL KITS'>ADMIN - BOATING EQUIPMENT-SPILL KITS</option>
					<option value='ADMIN BOATING EQUIPMENT-SURFBOARD'>ADMIN - BOATING EQUIPMENT-SURFBOARD</option>
					<option value='ADMIN BOATING EQUIPMENT-SURFSKI'>ADMIN - BOATING EQUIPMENT-SURFSKI</option>
					<option value='ADMIN CAMPING EQUIPMENT-BACKPACKS-LARGE'>ADMIN - CAMPING EQUIPMENT-BACKPACKS-LARGE</option>
					<option value='ADMIN CAMPING EQUIPMENT-COOKING STOVE/HOTPLATE-LARGE'>ADMIN - CAMPING EQUIPMENT-COOKING STOVE/HOTPLATE-LARGE</option>
					<option value='ADMIN CAMPING EQUIPMENT-FRIDGE/FREEZER-GAS/PORTABLE'>ADMIN - CAMPING EQUIPMENT-FRIDGE/FREEZER-GAS/PORTABLE</option>
					<option value='ADMIN CAMPING EQUIPMENT-GAS BOTTLE-LARGE'>ADMIN - CAMPING EQUIPMENT-GAS BOTTLE-LARGE</option>
					<option value='ADMIN CAMPING EQUIPMENT-GAS BOTTLE-SMALL'>ADMIN - CAMPING EQUIPMENT-GAS BOTTLE-SMALL</option>
					<option value='ADMIN CAMPING EQUIPMENT-LANTERN-DUAL FUEL'>ADMIN - CAMPING EQUIPMENT-LANTERN-DUAL FUEL</option>
					<option value='ADMIN CAMPING EQUIPMENT-LANTERN- GAS'>ADMIN - CAMPING EQUIPMENT-LANTERN- GAS</option>
					<option value='ADMIN CAMPING EQUIPMENT-SLEEPING BAGS'>ADMIN - CAMPING EQUIPMENT-SLEEPING BAGS</option>
					<option value='ADMIN CAMPING EQUIPMENT-STRETCHES'>ADMIN - CAMPING EQUIPMENT-STRETCHES</option>
					<option value='ADMIN CAMPING EQUIPMENT-TENTS-LARGE >10 MAN'>ADMIN - CAMPING EQUIPMENT-TENTS-LARGE >10 MAN</option>
					<option value='ADMIN CAMPING EQUIPMENT-TENTS-SMALL <10 MAN'>ADMIN - CAMPING EQUIPMENT-TENTS-SMALL <10 MAN</option>
					<option value='ADMIN CHAIR-BENCH-WOOD WITH OR WITHOUT UPHOLSTERY'>ADMIN - CHAIR-BENCH-WOOD WITH OR WITHOUT UPHOLSTERY</option>
					<option value='ADMIN CHAIR-TASK'>ADMIN - CHAIR-TASK</option>
					<option value='ADMIN CHAIR-CHURCH PEW'>ADMIN - CHAIR-CHURCH PEW</option>
					<option value='ADMIN CHAIR-CINEMA SEATING'>ADMIN - CHAIR-CINEMA SEATING</option>
					<option value='ADMIN CHAIR-CONFERENCE-FABRIC OR VINYL'>ADMIN - CHAIR-CONFERENCE-FABRIC OR VINYL</option>
					<option value='ADMIN CHAIR-CONFERENCE-LEATHER'>ADMIN - CHAIR-CONFERENCE-LEATHER</option>
					<option value='ADMIN CHAIR-DINING'>ADMIN - CHAIR-DINING</option>
					<option value='ADMIN CHAIR-DRAFTING'>ADMIN - CHAIR-DRAFTING</option>
					<option value='ADMIN CHAIR-HOSPITALITY'>ADMIN - CHAIR-HOSPITALITY</option>
					<option value='ADMIN CHAIR-OUTDOOR-PLASTIC'>ADMIN - CHAIR-OUTDOOR-PLASTIC</option>
					<option value='ADMIN CHAIR-OUTDOOR-WOOD'>ADMIN - CHAIR-OUTDOOR-WOOD</option>
					<option value='ADMIN CHAIR-STUDENT'>ADMIN - CHAIR-STUDENT</option>
					<option value='ADMIN CHAIR-TERMINAL SEATING'>ADMIN - CHAIR-TERMINAL SEATING</option>
					<option value='ADMIN CHAIR-THEATRE SEATING'>ADMIN - CHAIR-THEATRE SEATING</option>
					<option value='ADMIN CHAIR-FOOT STOOL'>ADMIN - CHAIR-FOOT STOOL</option>
					<option value='ADMIN CHAIR-LOUNGE-EXEC SINGLE-FABRIC OR VINYL'>ADMIN - CHAIR-LOUNGE-EXEC SINGLE-FABRIC OR VINYL</option>
					<option value='ADMIN CHAIR-LOUNGE-EXECUTIVE-MULTI-SEAT-LEATHER'>ADMIN - CHAIR-LOUNGE-EXECUTIVE-MULTI-SEAT-LEATHER</option>
					<option value='ADMIN CHAIR-LOUNGE-MULTI SEAT-FABRIC OR VINYL'>ADMIN - CHAIR-LOUNGE-MULTI SEAT-FABRIC OR VINYL</option>
					<option value='ADMIN CHAIR-LOUNGE-SINGLE SEAT-FABRIC OR VINYL'>ADMIN - CHAIR-LOUNGE-SINGLE SEAT-FABRIC OR VINYL</option>
					<option value='ADMIN CHAIR-STOOL-BAR-UPHOLSTERED'>ADMIN - CHAIR-STOOL-BAR-UPHOLSTERED</option>
					<option value='ADMIN CHAIR-STOOL-WOOD OR METAL'>ADMIN - CHAIR-STOOL-WOOD OR METAL</option>
					<option value='ADMIN CHAIR-SUN LOUNGE'>ADMIN - CHAIR-SUN LOUNGE</option>
					<option value='ADMIN CHAIR-SWISS BALL'>ADMIN - CHAIR-SWISS BALL</option>
					<option value='ADMIN CHAIRMAT'>ADMIN - CHAIRMAT</option>
					<option value='ADMIN DESK-EXECUTIVE'>ADMIN - DESK-EXECUTIVE</option>
					<option value='ADMIN DESK-OPEN'>ADMIN - DESK-OPEN</option>
					<option value='ADMIN DESK-UPRIGHT COMPUTER'>ADMIN - DESK-UPRIGHT COMPUTER</option>
					<option value='ADMIN DESK-RECEPTION DESK-TIMBER'>ADMIN - DESK-RECEPTION DESK-TIMBER</option>
					<option value='ADMIN DRESSING TABLE'>ADMIN - DRESSING TABLE</option>
					<option value='ADMIN GROUND MAINTENANCE-AIR COMPRESSOR'>ADMIN - GROUND MAINTENANCE-AIR COMPRESSOR</option>
					<option value='ADMIN GROUND MAINTENANCE-BAND SOW'>ADMIN - GROUND MAINTENANCE-BAND SOW</option>
					<option value='ADMIN GROUND MAINTENANCE-CENTRE LATHE'>ADMIN - GROUND MAINTENANCE-CENTRE LATHE</option>
					<option value='ADMIN GROUND MAINTENANCE-CIRCULAR SOW BENCH'>ADMIN - GROUND MAINTENANCE-CIRCULAR SOW BENCH</option>
					<option value='ADMIN GROUND MAINTENANCE-EDGE SANDER'>ADMIN - GROUND MAINTENANCE-EDGE SANDER</option>
					<option value='ADMIN GROUND MAINTENANCE-FIRE PUMP'>ADMIN - GROUND MAINTENANCE-FIRE PUMP</option>
					<option value='ADMIN GROUND MAINTENANCE-GRASS ROLLER'>ADMIN - GROUND MAINTENANCE-GRASS ROLLER</option>
					<option value='ADMIN GROUND MAINTENANCE-LAWN MOWER-PUSH'>ADMIN - GROUND MAINTENANCE-LAWN MOWER-PUSH</option>
					<option value='ADMIN GROUND MAINTENANCE-LAWN MOWER-RIDE-ON'>ADMIN - GROUND MAINTENANCE-LAWN MOWER-RIDE-ON</option>
					<option value='ADMIN GROUND MAINTENANCE-PRESSURE WASHER'>ADMIN - GROUND MAINTENANCE-PRESSURE WASHER</option>
					<option value='ADMIN GROUND MAINTENANCE-SCALES-PLATFORM  150KG'>ADMIN - GROUND MAINTENANCE-SCALES-PLATFORM  150KG</option>
					<option value='ADMIN GROUND MAINTENANCE-SMOKE MACHINE'>ADMIN - GROUND MAINTENANCE-SMOKE MACHINE</option>
					<option value='ADMIN GROUND MAINTENANCE-THICKNESSER MACHINE'>ADMIN - GROUND MAINTENANCE-THICKNESSER MACHINE</option>
					<option value='ADMIN GROUND MAINTENANCE-WEED EATER'>ADMIN - GROUND MAINTENANCE-WEED EATER</option>
					<option value='ADMIN GROUND MAINTENANCE-WOOD PLANER'>ADMIN - GROUND MAINTENANCE-WOOD PLANER</option>
					<option value='ADMIN GROUND MAINTENANCE-YARD VACUUM'>ADMIN - GROUND MAINTENANCE-YARD VACUUM</option>
					<option value='ADMIN GYM EQUIPMENT-ABDOMINAL CURLS'>ADMIN - GYM EQUIPMENT-ABDOMINAL CURLS</option>
					<option value='ADMIN GYM EQUIPMENT-ADJUSTABLE BENCH'>ADMIN - GYM EQUIPMENT-ADJUSTABLE BENCH</option>
					<option value='ADMIN GYM EQUIPMENT-ADOMINISER'>ADMIN - GYM EQUIPMENT-ADOMINISER</option>
					<option value='ADMIN GYM EQUIPMENT-ARM CURL/TRICEP PULL DOWN'>ADMIN - GYM EQUIPMENT-ARM CURL/TRICEP PULL DOWN</option>
					<option value='ADMIN GYM EQUIPMENT-ASSISTED DIP'>ADMIN - GYM EQUIPMENT-ASSISTED DIP</option>
					<option value='ADMIN GYM EQUIPMENT-BARBELL'>ADMIN - GYM EQUIPMENT-BARBELL</option>
					<option value='ADMIN GYM EQUIPMENT-BARBELL RACK'>ADMIN - GYM EQUIPMENT-BARBELL RACK</option>
					<option value='ADMIN GYM EQUIPMENT-BARBELL WEIGHTBAR'>ADMIN - GYM EQUIPMENT-BARBELL WEIGHTBAR</option>
					<option value='ADMIN GYM EQUIPMENT-BENCH PRESS'>ADMIN - GYM EQUIPMENT-BENCH PRESS</option>
					<option value='ADMIN GYM EQUIPMENT-BIKE-DUAL ACTION FAN'>ADMIN - GYM EQUIPMENT-BIKE-DUAL ACTION FAN</option>
					<option value='ADMIN GYM EQUIPMENT-BIKE-HAND (GRINDER)'>ADMIN - GYM EQUIPMENT-BIKE-HAND (GRINDER)</option>
					<option value='ADMIN GYM EQUIPMENT-BIKE-MAGNETIC'>ADMIN - GYM EQUIPMENT-BIKE-MAGNETIC</option>
					<option value='ADMIN GYM EQUIPMENT-BIKE-POWER BIKE'>ADMIN - GYM EQUIPMENT-BIKE-POWER BIKE</option>
					<option value='ADMIN GYM EQUIPMENT-BIKE-PROGRAMMABLE RECUMBENT'>ADMIN - GYM EQUIPMENT-BIKE-PROGRAMMABLE RECUMBENT</option>
					<option value='ADMIN GYM EQUIPMENT-BUTTERFLY MACHINE'>ADMIN - GYM EQUIPMENT-BUTTERFLY MACHINE</option>
					<option value='ADMIN GYM EQUIPMENT-CHEST PRESS'>ADMIN - GYM EQUIPMENT-CHEST PRESS</option>
					<option value='ADMIN GYM EQUIPMENT-CHINUP BAR'>ADMIN - GYM EQUIPMENT-CHINUP BAR</option>
					<option value='ADMIN GYM EQUIPMENT-CLIMBER'>ADMIN - GYM EQUIPMENT-CLIMBER</option>
					<option value='ADMIN GYM EQUIPMENT-CLIMBING MACHINE'>ADMIN - GYM EQUIPMENT-CLIMBING MACHINE</option>
					<option value='ADMIN GYM EQUIPMENT-CRASH MAT'>ADMIN - GYM EQUIPMENT-CRASH MAT</option>
					<option value='ADMIN GYM EQUIPMENT-DUMBBELLS-HANDWEIGHTS'>ADMIN - GYM EQUIPMENT-DUMBBELLS-HANDWEIGHTS</option>
					<option value='ADMIN GYM EQUIPMENT-ELECTRONIC SCOREBOARD'>ADMIN - GYM EQUIPMENT-ELECTRONIC SCOREBOARD</option>
					<option value='ADMIN GYM EQUIPMENT-ELLIPTICAL TRAINER-DUAL ACTION'>ADMIN - GYM EQUIPMENT-ELLIPTICAL TRAINER-DUAL ACTION</option>
					<option value='ADMIN GYM EQUIPMENT-FLAT BENCH PRESS'>ADMIN - GYM EQUIPMENT-FLAT BENCH PRESS</option>
					<option value='ADMIN GYM EQUIPMENT-FREE WEIGHT CHEST PRESS'>ADMIN - GYM EQUIPMENT-FREE WEIGHT CHEST PRESS</option>
					<option value='ADMIN GYM EQUIPMENT-FREE WEIGHT SHOULDER PRESS'>ADMIN - GYM EQUIPMENT-FREE WEIGHT SHOULDER PRESS</option>
					<option value='ADMIN GYM EQUIPMENT-FREE WEIGHTS 10KG'>ADMIN - GYM EQUIPMENT-FREE WEIGHTS 10KG</option>
					<option value='ADMIN GYM EQUIPMENT-FREE WEIGHTS 15KG'>ADMIN - GYM EQUIPMENT-FREE WEIGHTS 15KG</option>
					<option value='ADMIN GYM EQUIPMENT-FREE WEIGHTS 2.5KG'>ADMIN - GYM EQUIPMENT-FREE WEIGHTS 2.5KG</option>
					<option value='ADMIN GYM EQUIPMENT-FREE WEIGHTS 20KG'>ADMIN - GYM EQUIPMENT-FREE WEIGHTS 20KG</option>
					<option value='ADMIN GYM EQUIPMENT-FREE WEIGHTS 25KG'>ADMIN - GYM EQUIPMENT-FREE WEIGHTS 25KG</option>
					<option value='ADMIN GYM EQUIPMENT-FREE WEIGHTS 5KG'>ADMIN - GYM EQUIPMENT-FREE WEIGHTS 5KG</option>
					<option value='ADMIN GYM EQUIPMENT-HAND BIKE'>ADMIN - GYM EQUIPMENT-HAND BIKE</option>
					<option value='ADMIN GYM EQUIPMENT-HIGH PULLEY'>ADMIN - GYM EQUIPMENT-HIGH PULLEY</option>
					<option value='ADMIN GYM EQUIPMENT-HIP FLEXER'>ADMIN - GYM EQUIPMENT-HIP FLEXER</option>
					<option value='ADMIN GYM EQUIPMENT-INCLINE BENCH'>ADMIN - GYM EQUIPMENT-INCLINE BENCH</option>
					<option value='ADMIN GYM EQUIPMENT-INVERTED LEG PRESS'>ADMIN - GYM EQUIPMENT-INVERTED LEG PRESS</option>
					<option value='ADMIN GYM EQUIPMENT-INVERTED SITUP BENCH'>ADMIN - GYM EQUIPMENT-INVERTED SITUP BENCH</option>
					<option value='ADMIN GYM EQUIPMENT-LAT PULL DOWN MACHINE'>ADMIN - GYM EQUIPMENT-LAT PULL DOWN MACHINE</option>
					<option value='ADMIN GYM EQUIPMENT-LATERAL DELTOID RAISE MACHINE'>ADMIN - GYM EQUIPMENT-LATERAL DELTOID RAISE MACHINE</option>
					<option value='ADMIN GYM EQUIPMENT-LEG CURL'>ADMIN - GYM EQUIPMENT-LEG CURL</option>
					<option value='ADMIN GYM EQUIPMENT-LEG EXTENSION'>ADMIN - GYM EQUIPMENT-LEG EXTENSION</option>
					<option value='ADMIN GYM EQUIPMENT-LEG PRESS'>ADMIN - GYM EQUIPMENT-LEG PRESS</option>
					<option value='ADMIN GYM EQUIPMENT-LEG SQUAT'>ADMIN - GYM EQUIPMENT-LEG SQUAT</option>
					<option value='ADMIN GYM EQUIPMENT-MULTISTATION 2 FUNCTIONS'>ADMIN - GYM EQUIPMENT-MULTISTATION 2 FUNCTIONS</option>
					<option value='ADMIN GYM EQUIPMENT-MULTISTATION 3 FUNCTIONS'>ADMIN - GYM EQUIPMENT-MULTISTATION 3 FUNCTIONS</option>
					<option value='ADMIN GYM EQUIPMENT-MULTISTATION 4 FUNCTIONS'>ADMIN - GYM EQUIPMENT-MULTISTATION 4 FUNCTIONS</option>
					<option value='ADMIN GYM EQUIPMENT-MULTISTATION 5 FUNCTIONS'>ADMIN - GYM EQUIPMENT-MULTISTATION 5 FUNCTIONS</option>
					<option value='ADMIN GYM EQUIPMENT-MULTISTATION 6 FUNCTIONS'>ADMIN - GYM EQUIPMENT-MULTISTATION 6 FUNCTIONS</option>
					<option value='ADMIN GYM EQUIPMENT-MULTISTATION 7 FUNCTIONS'>ADMIN - GYM EQUIPMENT-MULTISTATION 7 FUNCTIONS</option>
					<option value='ADMIN GYM EQUIPMENT-MULTISTATION 8+ FUNCTIONS'>ADMIN - GYM EQUIPMENT-MULTISTATION 8+ FUNCTIONS</option>
					<option value='ADMIN GYM EQUIPMENT-PEC DECK'>ADMIN - GYM EQUIPMENT-PEC DECK</option>
					<option value='ADMIN GYM EQUIPMENT-PEC/REAR DELTOID FLY COMBINATION'>ADMIN - GYM EQUIPMENT-PEC/REAR DELTOID FLY COMBINATION</option>
					<option value='ADMIN GYM EQUIPMENT-PILATES MACHINE'>ADMIN - GYM EQUIPMENT-PILATES MACHINE</option>
					<option value='ADMIN GYM EQUIPMENT-PORTABLE BASKETBALL RING'>ADMIN - GYM EQUIPMENT-PORTABLE BASKETBALL RING</option>
					<option value='ADMIN GYM EQUIPMENT-PREACHER CURL'>ADMIN - GYM EQUIPMENT-PREACHER CURL</option>
					<option value='ADMIN GYM EQUIPMENT-REVERSE SITUP BENCH'>ADMIN - GYM EQUIPMENT-REVERSE SITUP BENCH</option>
					<option value='ADMIN GYM EQUIPMENT-ROWER-ELECTRONIC & PROGRAMMABLE'>ADMIN - GYM EQUIPMENT-ROWER-ELECTRONIC & PROGRAMMABLE</option>
					<option value='ADMIN GYM EQUIPMENT-ROWER-HYDRAULIC'>ADMIN - GYM EQUIPMENT-ROWER-HYDRAULIC</option>
					<option value='ADMIN GYM EQUIPMENT-SECURITY SYSTEM'>ADMIN - GYM EQUIPMENT-SECURITY SYSTEM</option>
					<option value='ADMIN GYM EQUIPMENT-SEATED BACK'>ADMIN - GYM EQUIPMENT-SEATED BACK</option>
					<option value='ADMIN GYM EQUIPMENT-SEATED CALF RAISER'>ADMIN - GYM EQUIPMENT-SEATED CALF RAISER</option>
					<option value='ADMIN GYM EQUIPMENT-SEATED FREEWEIGHT SHOLDER PRESS'>ADMIN - GYM EQUIPMENT-SEATED FREEWEIGHT SHOLDER PRESS</option>
					<option value='ADMIN GYM EQUIPMENT-SEATED ROW'>ADMIN - GYM EQUIPMENT-SEATED ROW</option>
					<option value='ADMIN GYM EQUIPMENT-SHOULDER PRESS'>ADMIN - GYM EQUIPMENT-SHOULDER PRESS</option>
					<option value='ADMIN GYM EQUIPMENT-SITUP BENCH'>ADMIN - GYM EQUIPMENT-SITUP BENCH</option>
					<option value='ADMIN GYM EQUIPMENT-SKI MACHINE'>ADMIN - GYM EQUIPMENT-SKI MACHINE</option>
					<option value='ADMIN GYM EQUIPMENT-SMITH MACHINE'>ADMIN - GYM EQUIPMENT-SMITH MACHINE</option>
					<option value='ADMIN GYM EQUIPMENT-SPINNER BIKE'>ADMIN - GYM EQUIPMENT-SPINNER BIKE</option>
					<option value='ADMIN GYM EQUIPMENT-SQUAT RACK'>ADMIN - GYM EQUIPMENT-SQUAT RACK</option>
					<option value='ADMIN GYM EQUIPMENT-STEPPER-ELECTRONIC & PROGRAMMABLE'>ADMIN - GYM EQUIPMENT-STEPPER-ELECTRONIC & PROGRAMMABLE</option>
					<option value='ADMIN GYM EQUIPMENT-STEPPER-MANUAL'>ADMIN - GYM EQUIPMENT-STEPPER-MANUAL</option>
					<option value='ADMIN GYM EQUIPMENT-T BAR DEAD LIFT'>ADMIN - GYM EQUIPMENT-T BAR DEAD LIFT</option>
					<option value='ADMIN GYM EQUIPMENT-TOTAL HIP MACHINE'>ADMIN - GYM EQUIPMENT-TOTAL HIP MACHINE</option>
					<option value='ADMIN GYM EQUIPMENT-TRAMPOLINE-LARGE'>ADMIN - GYM EQUIPMENT-TRAMPOLINE-LARGE</option>
					<option value='ADMIN GYM EQUIPMENT-TRAMPOLINE-MINI'>ADMIN - GYM EQUIPMENT-TRAMPOLINE-MINI</option>
					<option value='ADMIN GYM EQUIPMENT-TREADMILL-AUTO INCLINE'>ADMIN - GYM EQUIPMENT-TREADMILL-AUTO INCLINE</option>
					<option value='ADMIN GYM EQUIPMENT-TREADMILL-ELECTRONIC & PROGRAMMABLE'>ADMIN - GYM EQUIPMENT-TREADMILL-ELECTRONIC & PROGRAMMABLE</option>
					<option value='ADMIN GYM EQUIPMENT-TREADMILL-MANUAL'>ADMIN - GYM EQUIPMENT-TREADMILL-MANUAL</option>
					<option value='ADMIN GYM EQUIPMENT-TREADMILL-PROGRAMMABLE & FOLDAWAY'>ADMIN - GYM EQUIPMENT-TREADMILL-PROGRAMMABLE & FOLDAWAY</option>
					<option value='ADMIN GYM EQUIPMENT-UPRIGHT ROW'>ADMIN - GYM EQUIPMENT-UPRIGHT ROW</option>
					<option value='ADMIN GYM EQUIPMENT-WEIGHT STORAGE TREE'>ADMIN - GYM EQUIPMENT-WEIGHT STORAGE TREE</option>
					<option value='ADMIN GYM EQUIPMENT-WEIGHT TRAINING BENCH'>ADMIN - GYM EQUIPMENT-WEIGHT TRAINING BENCH</option>
					<option value='ADMIN GYM EQUIPMENT-WEIGHTS-SOLID HAND (SET OF 12 PAIRS)'>ADMIN - GYM EQUIPMENT-WEIGHTS-SOLID HAND (SET OF 12 PAIRS)</option>
					<option value='ADMIN HAT RACK'>ADMIN - HAT RACK</option>
					<option value='ADMIN HERITAGE'>ADMIN - HERITAGE</option>
					<option value='ADMIN INDUSTRIAL VEHICLE-BULLDOZER'>ADMIN - INDUSTRIAL VEHICLE-BULLDOZER</option>
					<option value='ADMIN INDUSTRIAL VEHICLE-FIRE TRUCK'>ADMIN - INDUSTRIAL VEHICLE-FIRE TRUCK</option>
					<option value='ADMIN INDUSTRIAL VEHICLE-FORKLIFT'>ADMIN - INDUSTRIAL VEHICLE-FORKLIFT</option>
					<option value='ADMIN INDUSTRIAL VEHICLE-FORKLIFT-INDUSTRIAL'>ADMIN - INDUSTRIAL VEHICLE-FORKLIFT-INDUSTRIAL</option>
					<option value='ADMIN INDUSTRIAL VEHICLE-GRADER'>ADMIN - INDUSTRIAL VEHICLE-GRADER</option>
					<option value='ADMIN INDUSTRIAL VEHICLE-MOBILISER'>ADMIN - INDUSTRIAL VEHICLE-MOBILISER</option>
					<option value='ADMIN INDUSTRIAL VEHICLE-TRACTOR'>ADMIN - INDUSTRIAL VEHICLE-TRACTOR</option>
					<option value='ADMIN KITCHEN EQUIPMENT-BAIN MARIE'>ADMIN - KITCHEN EQUIPMENT-BAIN MARIE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-BALE PRESS'>ADMIN - KITCHEN EQUIPMENT-BALE PRESS</option>
					<option value='ADMIN KITCHEN EQUIPMENT-BIN WASHER'>ADMIN - KITCHEN EQUIPMENT-BIN WASHER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-BLAST CHILLER'>ADMIN - KITCHEN EQUIPMENT-BLAST CHILLER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-BRAT PAN'>ADMIN - KITCHEN EQUIPMENT-BRAT PAN</option>
					<option value='ADMIN KITCHEN EQUIPMENT-BUTCHERS BLOCK'>ADMIN - KITCHEN EQUIPMENT-BUTCHERS BLOCK</option>
					<option value='ADMIN KITCHEN EQUIPMENT-COFFEE MACHINE'>ADMIN - KITCHEN EQUIPMENT-COFFEE MACHINE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-CHAR GRILL'>ADMIN - KITCHEN EQUIPMENT-CHAR GRILL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-CHEST FREEZER- SMALL'>ADMIN - KITCHEN EQUIPMENT-CHEST FREEZER- SMALL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-CHIP MAKER'>ADMIN - KITCHEN EQUIPMENT-CHIP MAKER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-CHIP WARMER'>ADMIN - KITCHEN EQUIPMENT-CHIP WARMER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-COOK TOP & OVEN-GAS'>ADMIN - KITCHEN EQUIPMENT-COOK TOP & OVEN-GAS</option>
					<option value='ADMIN KITCHEN EQUIPMENT-COOK TOP-DOMESTIC -ELECTRIC'>ADMIN - KITCHEN EQUIPMENT-COOK TOP-DOMESTIC -ELECTRIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-COOKTOP & OVEN-ELECTRIC'>ADMIN - KITCHEN EQUIPMENT-COOKTOP & OVEN-ELECTRIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-COOKTOP-ELECTRIC-BENCHTOP'>ADMIN - KITCHEN EQUIPMENT-COOKTOP-ELECTRIC-BENCHTOP</option>
					<option value='ADMIN KITCHEN EQUIPMENT-COOKTOP-GAS'>ADMIN - KITCHEN EQUIPMENT-COOKTOP-GAS</option>
					<option value='ADMIN KITCHEN EQUIPMENT-COOKTOP-GAS-BBQ'>ADMIN - KITCHEN EQUIPMENT-COOKTOP-GAS-BBQ</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DEEP FRYER-ELECTRIC'>ADMIN - KITCHEN EQUIPMENT-DEEP FRYER-ELECTRIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DEEP FRYER-GAS'>ADMIN - KITCHEN EQUIPMENT-DEEP FRYER-GAS</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DELI CABINET'>ADMIN - KITCHEN EQUIPMENT-DELI CABINET</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DISHWASHER-LARGE'>ADMIN - KITCHEN EQUIPMENT-DISHWASHER-LARGE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DISHWASHER-SMALL'>ADMIN - KITCHEN EQUIPMENT-DISHWASHER-SMALL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DONUT MACHINE'>ADMIN - KITCHEN EQUIPMENT-DONUT MACHINE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DRINK DISPENSER'>ADMIN - KITCHEN EQUIPMENT-DRINK DISPENSER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DUMB WAITER'>ADMIN - KITCHEN EQUIPMENT-DUMB WAITER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FAN-INDUSTRIAL'>ADMIN - KITCHEN EQUIPMENT-FAN-INDUSTRIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FLOOR CLEANER'>ADMIN - KITCHEN EQUIPMENT-FLOOR CLEANER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FLOUR BINS-STAINLESS/PLASTIC'>ADMIN - KITCHEN EQUIPMENT-FLOUR BINS-STAINLESS/PLASTIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FONDUE CABINET'>ADMIN - KITCHEN EQUIPMENT-FONDUE CABINET</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FOOD MIXER-BENCHTOP'>ADMIN - KITCHEN EQUIPMENT-FOOD MIXER-BENCHTOP</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FOOD MIXER-FLOOR MOUNTED'>ADMIN - KITCHEN EQUIPMENT-FOOD MIXER-FLOOR MOUNTED</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FOOD PROCESSOR-LARGE'>ADMIN - KITCHEN EQUIPMENT-FOOD PROCESSOR-LARGE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FOOD PROCESSOR-SMALL'>ADMIN - KITCHEN EQUIPMENT-FOOD PROCESSOR-SMALL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FREEZER-2 DOOR-COMMERCIAL'>ADMIN - KITCHEN EQUIPMENT-FREEZER-2 DOOR-COMMERCIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FREEZER-3 DOOR-COMMERCIAL'>ADMIN - KITCHEN EQUIPMENT-FREEZER-3 DOOR-COMMERCIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FREEZER-4 DOOR-COMMERCIAL'>ADMIN - KITCHEN EQUIPMENT-FREEZER-4 DOOR-COMMERCIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-FREEZER-SINGLE DOOR-COMMERCIAL'>ADMIN - KITCHEN EQUIPMENT-FREEZER-SINGLE DOOR-COMMERCIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-GARBAGE DISPOSAL UNIT'>ADMIN - KITCHEN EQUIPMENT-GARBAGE DISPOSAL UNIT</option>
					<option value='ADMIN KITCHEN EQUIPMENT-GLASS CHILLER'>ADMIN - KITCHEN EQUIPMENT-GLASS CHILLER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-GLASS WASHER'>ADMIN - KITCHEN EQUIPMENT-GLASS WASHER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-HAND HELD VITAMIZER (BARMIX)'>ADMIN - KITCHEN EQUIPMENT-HAND HELD VITAMIZER (BARMIX)</option>
					<option value='ADMIN KITCHEN EQUIPMENT-HOT CABINET'>ADMIN - KITCHEN EQUIPMENT-HOT CABINET</option>
					<option value='ADMIN KITCHEN EQUIPMENT-HOT PLATE-ELECTRIC'>ADMIN - KITCHEN EQUIPMENT-HOT PLATE-ELECTRIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-HOT PLATE-GAS'>ADMIN - KITCHEN EQUIPMENT-HOT PLATE-GAS</option>
					<option value='ADMIN KITCHEN EQUIPMENT-ICE MACHINE-LARGE'>ADMIN - KITCHEN EQUIPMENT-ICE MACHINE-LARGE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-ICE MACHINE-SMALL'>ADMIN - KITCHEN EQUIPMENT-ICE MACHINE-SMALL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-INSECTOCUTER-BUG ZAPPER'>ADMIN - KITCHEN EQUIPMENT-INSECTOCUTER-BUG ZAPPER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-MEAT TENDERIZER'>ADMIN - KITCHEN EQUIPMENT-MEAT TENDERIZER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-MICROWAVE OVEN-INDUSTRIAL'>ADMIN - KITCHEN EQUIPMENT-MICROWAVE OVEN-INDUSTRIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-MINCER'>ADMIN - KITCHEN EQUIPMENT-MINCER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-OIL FILTRATION UNIT'>ADMIN - KITCHEN EQUIPMENT-OIL FILTRATION UNIT</option>
					<option value='ADMIN KITCHEN EQUIPMENT-OVEN-CONVECTIONAL-ELECTRIC-LARGE'>ADMIN - KITCHEN EQUIPMENT-OVEN-CONVECTIONAL-ELECTRIC-LARGE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-OVEN-ELECTRIC'>ADMIN - KITCHEN EQUIPMENT-OVEN-ELECTRIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-OVEN-GAS'>ADMIN - KITCHEN EQUIPMENT-OVEN-GAS</option>
					<option value='ADMIN KITCHEN EQUIPMENT-OVEN-STEAMER-GAS OR ELECTRIC'>ADMIN - KITCHEN EQUIPMENT-OVEN-STEAMER-GAS OR ELECTRIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-OVEN COOKTOP-6+ BURNER'>ADMIN - KITCHEN EQUIPMENT-OVEN COOKTOP-6+ BURNER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-OVEN- PIZZA'>ADMIN - KITCHEN EQUIPMENT-OVEN- PIZZA</option>
					<option value='ADMIN KITCHEN EQUIPMENT-PALLET WRAP MACHINE'>ADMIN - KITCHEN EQUIPMENT-PALLET WRAP MACHINE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-PASTRY ROLLER'>ADMIN - KITCHEN EQUIPMENT-PASTRY ROLLER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-PIE WARMER'>ADMIN - KITCHEN EQUIPMENT-PIE WARMER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-PLATE WARMER'>ADMIN - KITCHEN EQUIPMENT-PLATE WARMER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-POT WASHER'>ADMIN - KITCHEN EQUIPMENT-POT WASHER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-POTATO RUBLER'>ADMIN - KITCHEN EQUIPMENT-POTATO RUBLER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-POWER SOAK'>ADMIN - KITCHEN EQUIPMENT-POWER SOAK</option>
					<option value='ADMIN KITCHEN EQUIPMENT-PREPARATION BENCH-MARBLE'>ADMIN - KITCHEN EQUIPMENT-PREPARATION BENCH-MARBLE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-PREPARATION BENCH-S/STEEL'>ADMIN - KITCHEN EQUIPMENT-PREPARATION BENCH-S/STEEL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-PROOFING CABINET'>ADMIN - KITCHEN EQUIPMENT-PROOFING CABINET</option>
					<option value='ADMIN KITCHEN EQUIPMENT-PROOVER CABINET'>ADMIN - KITCHEN EQUIPMENT-PROOVER CABINET</option>
					<option value='ADMIN KITCHEN EQUIPMENT-REFRIGERATION-2 DOOR-COMMERCIAL'>ADMIN - KITCHEN EQUIPMENT-REFRIGERATION-2 DOOR-COMMERCIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-REFRIGERATION-3 DOOR-COMMERCIAL'>ADMIN - KITCHEN EQUIPMENT-REFRIGERATION-3 DOOR-COMMERCIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-REFRIGERATION-4 DOOR-COMMERCIAL'>ADMIN - KITCHEN EQUIPMENT-REFRIGERATION-4 DOOR-COMMERCIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-REFRIGERATION-FABRICATED COOL RM'>ADMIN - KITCHEN EQUIPMENT-REFRIGERATION-FABRICATED COOL RM</option>
					<option value='ADMIN KITCHEN EQUIPMENT-REFRIGERATION-TEMPRITES'>ADMIN - KITCHEN EQUIPMENT-REFRIGERATION-TEMPRITES</option>
					<option value='ADMIN KITCHEN EQUIPMENT-REFRIGERATOR-CAKE'>ADMIN - KITCHEN EQUIPMENT-REFRIGERATOR-CAKE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-REFRIGERATOR-COMMERCIAL 4 DOOR +'>ADMIN - KITCHEN EQUIPMENT-REFRIGERATOR-COMMERCIAL 4 DOOR +</option>
					<option value='ADMIN KITCHEN EQUIPMENT-REFRIGERATOR-DELI CABINET'>ADMIN - KITCHEN EQUIPMENT-REFRIGERATOR-DELI CABINET</option>
					<option value='ADMIN KITCHEN EQUIPMENT-REFRIGERATOR-SINGLE DOOR-COMMERC'>ADMIN - KITCHEN EQUIPMENT-REFRIGERATOR-SINGLE DOOR-COMMERC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-RICE COOKER'>ADMIN - KITCHEN EQUIPMENT-RICE COOKER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SALAMANDER-ELECTRIC'>ADMIN - KITCHEN EQUIPMENT-SALAMANDER-ELECTRIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SALAMANDER-GAS'>ADMIN - KITCHEN EQUIPMENT-SALAMANDER-GAS</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SANDWICH PRESS'>ADMIN - KITCHEN EQUIPMENT-SANDWICH PRESS</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SCALES-MEAT'>ADMIN - KITCHEN EQUIPMENT-SCALES-MEAT</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SCALES-MEAT FRAME'>ADMIN - KITCHEN EQUIPMENT-SCALES-MEAT FRAME</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SCALES-PLATFORM  150KG'>ADMIN - KITCHEN EQUIPMENT-SCALES-PLATFORM  150KG</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SCALES KITCHEN-30KG-50KG'>ADMIN - KITCHEN EQUIPMENT-SCALES KITCHEN-30KG-50KG</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SERVERY -S/STEEL-BAIN MARIE'>ADMIN - KITCHEN EQUIPMENT-SERVERY -S/STEEL-BAIN MARIE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SERVERY-INSULATED'>ADMIN - KITCHEN EQUIPMENT-SERVERY-INSULATED</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SERVERY-ISLAND HOT FOOD'>ADMIN - KITCHEN EQUIPMENT-SERVERY-ISLAND HOT FOOD</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SEVERY ISLAND-COLD FOOD'>ADMIN - KITCHEN EQUIPMENT-SEVERY ISLAND-COLD FOOD</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SLICER'>ADMIN - KITCHEN EQUIPMENT-SLICER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SOFT SERVE DISPENSER'>ADMIN - KITCHEN EQUIPMENT-SOFT SERVE DISPENSER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SOUP KETTLE'>ADMIN - KITCHEN EQUIPMENT-SOUP KETTLE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-SUPER CHILLER'>ADMIN - KITCHEN EQUIPMENT-SUPER CHILLER</option>
					<option value='ADMIN KITCHEN EQUIPMENT-TOASTER-INDUSTRIAL'>ADMIN - KITCHEN EQUIPMENT-TOASTER-INDUSTRIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-URN'>ADMIN - KITCHEN EQUIPMENT-URN</option>
					<option value='ADMIN KITCHEN EQUIPMENT-VACUUM SEALING MACHINE'>ADMIN - KITCHEN EQUIPMENT-VACUUM SEALING MACHINE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-WAFFLE IRON-INDUSTRIAL'>ADMIN - KITCHEN EQUIPMENT-WAFFLE IRON-INDUSTRIAL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-WOK STOVE'>ADMIN - KITCHEN EQUIPMENT-WOK STOVE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DOMESTIC-CHEST FREEZER-LARGE'>ADMIN - KITCHEN EQUIPMENT-DOMESTIC-CHEST FREEZER-LARGE</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DOMESTIC-CHEST FREEZER-MEDIUM'>ADMIN - KITCHEN EQUIPMENT-DOMESTIC-CHEST FREEZER-MEDIUM</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DOMESTIC-CHEST FREEZER-SMALL'>ADMIN - KITCHEN EQUIPMENT-DOMESTIC-CHEST FREEZER-SMALL</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DOMESTIC-DISHWASHER-DOMESTIC'>ADMIN - KITCHEN EQUIPMENT-DOMESTIC-DISHWASHER-DOMESTIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DOMESTIC-MICROWAVE OVEN-DOMESTIC'>ADMIN - KITCHEN EQUIPMENT-DOMESTIC-MICROWAVE OVEN-DOMESTIC</option>
					<option value='ADMIN KITCHEN EQUIPMENT-DOMESTIC-REFRIGERATOR-BAR'>ADMIN - KITCHEN EQUIPMENT-DOMESTIC-REFRIGERATOR-BAR</option>
					<option value='ADMIN LADDER-A FRAME'>ADMIN - LADDER-A FRAME</option>
					<option value='ADMIN LADDER-EXTENSION'>ADMIN - LADDER-EXTENSION</option>
					<option value='ADMIN LADDER-SINGLE/MULTI SECTIONS'>ADMIN - LADDER-SINGLE/MULTI SECTIONS</option>
					<option value='ADMIN LADDER-STEPS-MOBILE'>ADMIN - LADDER-STEPS-MOBILE</option>
					<option value='ADMIN LADDER-STEPS-MOBILE WAREHOUSE'>ADMIN - LADDER-STEPS-MOBILE WAREHOUSE</option>
					<option value='ADMIN LADDER-STEPS-KITCHEN'>ADMIN - LADDER-STEPS-KITCHEN</option>
					<option value='ADMIN LAUNDRY EQUIPMENT-CLOTHES DRYER-LARGE'>ADMIN - LAUNDRY EQUIPMENT-CLOTHES DRYER-LARGE</option>
					<option value='ADMIN LAUNDRY EQUIPMENT-CLOTHES DRYER-SMALL'>ADMIN - LAUNDRY EQUIPMENT-CLOTHES DRYER-SMALL</option>
					<option value='ADMIN LAUNDRY EQUIPMENT-VACUUM CLEANER-DOMESTIC'>ADMIN - LAUNDRY EQUIPMENT-VACUUM CLEANER-DOMESTIC</option>
					<option value='ADMIN LAUNDRY EQUIPMENT-VACUUM CLEANER-INDUSTRIAL'>ADMIN - LAUNDRY EQUIPMENT-VACUUM CLEANER-INDUSTRIAL</option>
					<option value='ADMIN LAUNDRY EQUIPMENT-WASHING MACHINE-LARGE'>ADMIN - LAUNDRY EQUIPMENT-WASHING MACHINE-LARGE</option>
					<option value='ADMIN LAUNDRY EQUIPMENT-WASHING MACHINE-SMALL'>ADMIN - LAUNDRY EQUIPMENT-WASHING MACHINE-SMALL</option>
					<option value='ADMIN LECTURN-ELECTRONIC LECTERN'>ADMIN - LECTURN-ELECTRONIC LECTERN</option>
					<option value='ADMIN LECTERN'>ADMIN - LECTERN</option>
					<option value='ADMIN LIGHT VEHICLE-4X4'>ADMIN - LIGHT VEHICLE-4X4</option>
					<option value='ADMIN LIGHT VEHICLE-AMBULANCE'>ADMIN - LIGHT VEHICLE-AMBULANCE</option>
					<option value='ADMIN LIGHT VEHICLE-COUPE'>ADMIN - LIGHT VEHICLE-COUPE</option>
					<option value='ADMIN LIGHT VEHICLE-HATCH'>ADMIN - LIGHT VEHICLE-HATCH</option>
					<option value='ADMIN LIGHT VEHICLE-SEDAN'>ADMIN - LIGHT VEHICLE-SEDAN</option>
					<option value='ADMIN LIGHT VEHICLE-UTILITY'>ADMIN - LIGHT VEHICLE-UTILITY</option>
					<option value='ADMIN LIGHT VEHICLE-VAN'>ADMIN - LIGHT VEHICLE-VAN</option>
					<option value='ADMIN LIGHT VEHICLE-WAGON'>ADMIN - LIGHT VEHICLE-WAGON</option>
					<option value='ADMIN MIRROR'>ADMIN - MIRROR</option>
					<option value='ADMIN OFFICE MACHINERY-BINDING MACHINE'>ADMIN - OFFICE MACHINERY-BINDING MACHINE</option>
					<option value='ADMIN OFFICE MACHINERY-CARD FILING DRAWERS'>ADMIN - OFFICE MACHINERY-CARD FILING DRAWERS</option>
					<option value='ADMIN OFFICE MACHINERY-DICTAPHONE'>ADMIN - OFFICE MACHINERY-DICTAPHONE</option>
					<option value='ADMIN OFFICE MACHINERY-EMBROIDERY MACHINE'>ADMIN - OFFICE MACHINERY-EMBROIDERY MACHINE</option>
					<option value='ADMIN OFFICE MACHINERY-FACSIMILE-HEAVY-SPEAKEASY'>ADMIN - OFFICE MACHINERY-FACSIMILE-HEAVY-SPEAKEASY</option>
					<option value='ADMIN OFFICE MACHINERY-FACSIMILE-LIGHT'>ADMIN - OFFICE MACHINERY-FACSIMILE-LIGHT</option>
					<option value='ADMIN OFFICE MACHINERY-FRANKING MACHINE'>ADMIN - OFFICE MACHINERY-FRANKING MACHINE</option>
					<option value='ADMIN OFFICE MACHINERY-GUILLOTINE-POWER OPERATED'>ADMIN - OFFICE MACHINERY-GUILLOTINE-POWER OPERATED</option>
					<option value='ADMIN OFFICE MACHINERY-HEAT BINDING MACHINE'>ADMIN - OFFICE MACHINERY-HEAT BINDING MACHINE</option>
					<option value='ADMIN OFFICE MACHINERY-HOLE PUNCH -ELECTRONIC'>ADMIN - OFFICE MACHINERY-HOLE PUNCH -ELECTRONIC</option>
					<option value='ADMIN OFFICE MACHINERY-LAMINATOR'>ADMIN - OFFICE MACHINERY-LAMINATOR</option>
					<option value='ADMIN OFFICE MACHINERY-MAIL SORTER'>ADMIN - OFFICE MACHINERY-MAIL SORTER</option>
					<option value='ADMIN OFFICE MACHINERY-MICROFICHE'>ADMIN - OFFICE MACHINERY-MICROFICHE</option>
					<option value='ADMIN OFFICE MACHINERY-OVERLOCKER'>ADMIN - OFFICE MACHINERY-OVERLOCKER</option>
					<option value='ADMIN OFFICE MACHINERY-PAPER SHREDDER'>ADMIN - OFFICE MACHINERY-PAPER SHREDDER</option>
					<option value='ADMIN OFFICE MACHINERY-PHOTOCOPIER-COLOUR'>ADMIN - OFFICE MACHINERY-PHOTOCOPIER-COLOUR</option>
					<option value='ADMIN OFFICE MACHINERY-PHOTOCOPIER-HEAVY-MULTI-FUNCTION'>ADMIN - OFFICE MACHINERY-PHOTOCOPIER-HEAVY-MULTI-FUNCTION</option>
					<option value='ADMIN OFFICE MACHINERY-PHOTOCOPIER-LIGHT'>ADMIN - OFFICE MACHINERY-PHOTOCOPIER-LIGHT</option>
					<option value='ADMIN OFFICE MACHINERY-PHOTOCOPIER-MEDIUM'>ADMIN - OFFICE MACHINERY-PHOTOCOPIER-MEDIUM</option>
					<option value='ADMIN OFFICE MACHINERY-PHOTOCOPIER-MULTI-FUNCTION'>ADMIN - OFFICE MACHINERY-PHOTOCOPIER-MULTI-FUNCTION</option>
					<option value='ADMIN OFFICE MACHINERY-PHOTOCOPIER-PLAN'>ADMIN - OFFICE MACHINERY-PHOTOCOPIER-PLAN</option>
					<option value='ADMIN OFFICE MACHINERY-SCALES-POSTAL  5KG'>ADMIN - OFFICE MACHINERY-SCALES-POSTAL  5KG</option>
					<option value='ADMIN OFFICE MACHINERY-SCANNER'>ADMIN - OFFICE MACHINERY-SCANNER</option>
					<option value='ADMIN OFFICE MACHINERY-SECURITY-X-RAY MACHINE'>ADMIN - OFFICE MACHINERY-SECURITY-X-RAY MACHINE</option>
					<option value='ADMIN OFFICE MACHINERY-SEWING MACHINE'>ADMIN - OFFICE MACHINERY-SEWING MACHINE</option>
					<option value='ADMIN PUBLISHING EQUIP-PLAN COPIER'>ADMIN - PUBLISHING EQUIP-PLAN COPIER</option>
					<option value='ADMIN PUBLISHING EQUIP-TYPE-SET MACHINERY'>ADMIN - PUBLISHING EQUIP-TYPE-SET MACHINERY</option>
					<option value='ADMIN ROOM DIVIDER-ROOM DIVIDER'>ADMIN - ROOM DIVIDER-ROOM DIVIDER</option>
					<option value='ADMIN SMALL ARMS RANGE EQUIPMENT-TORPEDO SLING'>ADMIN - SMALL ARMS RANGE EQUIPMENT-TORPEDO SLING</option>
					<option value='ADMIN SOUND EQUIPMENT-SOUND EQUIPMENT'>ADMIN - SOUND EQUIPMENT-SOUND EQUIPMENT</option>
					<option value='ADMIN SOUND RANGE EQUIPMENT-SOUND RANGE BUOYS'>ADMIN - SOUND RANGE EQUIPMENT-SOUND RANGE BUOYS</option>
					<option value='ADMIN SPECIALIST RANGE EQUIPMENT-DART MECHANISM'>ADMIN - SPECIALIST RANGE EQUIPMENT-DART MECHANISM</option>
					<option value='ADMIN SPECIALIST RANGE EQUIPMENT-FIRING SYSTEM'>ADMIN - SPECIALIST RANGE EQUIPMENT-FIRING SYSTEM</option>
					<option value='ADMIN SPECIALIST RANGE EQUIPMENT-PNEUMATIC TARGET MECHAN'>ADMIN - SPECIALIST RANGE EQUIPMENT-PNEUMATIC TARGET MECHAN</option>
					<option value='ADMIN SPECIALIST RANGE EQUIPMENT-VDU TARGET'>ADMIN - SPECIALIST RANGE EQUIPMENT-VDU TARGET</option>
					<option value='ADMIN OTHER REC EQUIP-BIKE-PUSH BIKE'>ADMIN - OTHER REC EQUIP-BIKE-PUSH BIKE</option>
					<option value='ADMIN OTHER REC EQUIP-AUDIO VISUAL TOUCH SCREEN'>ADMIN - OTHER REC EQUIP-AUDIO VISUAL TOUCH SCREEN</option>
					<option value='ADMIN OTHER REC EQUIP-CHESS TABLE'>ADMIN - OTHER REC EQUIP-CHESS TABLE</option>
					<option value='ADMIN OTHER REC EQUIP-DVD'>ADMIN - OTHER REC EQUIP-DVD</option>
					<option value='ADMIN OTHER REC EQUIP-PIANO-OTHER'>ADMIN - OTHER REC EQUIP-PIANO-OTHER</option>
					<option value='ADMIN OTHER REC EQUIP-PIANO-UPRIGHT'>ADMIN - OTHER REC EQUIP-PIANO-UPRIGHT</option>
					<option value='ADMIN OTHER REC EQUIP-PITCHING MACHINE'>ADMIN - OTHER REC EQUIP-PITCHING MACHINE</option>
					<option value='ADMIN OTHER REC EQUIP-PORTABLE STADIUM SEATING-STEEL'>ADMIN - OTHER REC EQUIP-PORTABLE STADIUM SEATING-STEEL</option>
					<option value='ADMIN OTHER REC EQUIP-PUBLIC ADDRESS SYSTEM'>ADMIN - OTHER REC EQUIP-PUBLIC ADDRESS SYSTEM</option>
					<option value='ADMIN OTHER REC EQUIP-SNOOKER/POOL TABLE'>ADMIN - OTHER REC EQUIP-SNOOKER/POOL TABLE</option>
					<option value='ADMIN OTHER REC EQUIP-STEREO SYSTEM'>ADMIN - OTHER REC EQUIP-STEREO SYSTEM</option>
					<option value='ADMIN OTHER REC EQUIP-TABLE TENNIS TABLE'>ADMIN - OTHER REC EQUIP-TABLE TENNIS TABLE</option>
					<option value='ADMIN OTHER REC EQUIP-TELEVISION -SMALL'>ADMIN - OTHER REC EQUIP-TELEVISION -SMALL</option>
					<option value='ADMIN OTHER REC EQUIP-TELEVISION & VIDEO'>ADMIN - OTHER REC EQUIP-TELEVISION & VIDEO</option>
					<option value='ADMIN OTHER REC EQUIP-TELEVISION- LARGE'>ADMIN - OTHER REC EQUIP-TELEVISION- LARGE</option>
					<option value='ADMIN OTHER REC EQUIP-TELEVISION-MEDIUM'>ADMIN - OTHER REC EQUIP-TELEVISION-MEDIUM</option>
					<option value='ADMIN OTHER REC EQUIP-TELEVISION-REAR PROJECTION'>ADMIN - OTHER REC EQUIP-TELEVISION-REAR PROJECTION</option>
					<option value='ADMIN OTHER REC EQUIP-VIDEO-VHS'>ADMIN - OTHER REC EQUIP-VIDEO-VHS</option>
					<option value='ADMIN STORAGE-BOOKCASE-OVERHEAD'>ADMIN - STORAGE-BOOKCASE-OVERHEAD</option>
					<option value='ADMIN STORAGE-BOOKCASE LOWBOY-EXECUTIVE'>ADMIN - STORAGE-BOOKCASE LOWBOY-EXECUTIVE</option>
					<option value='ADMIN STORAGE-BOOKCASE TALLBOY'>ADMIN - STORAGE-BOOKCASE TALLBOY</option>
					<option value='ADMIN STORAGE-CAGE'>ADMIN - STORAGE-CAGE</option>
					<option value='ADMIN STORAGE-CHEST OF DRAWERS'>ADMIN - STORAGE-CHEST OF DRAWERS</option>
					<option value='ADMIN STORAGE-COMPACTUS- 4-6  SECTIONS'>ADMIN - STORAGE-COMPACTUS- 4-6  SECTIONS</option>
					<option value='ADMIN STORAGE-COMPACTUS-10 +'>ADMIN - STORAGE-COMPACTUS-10 +</option>
					<option value='ADMIN STORAGE-COMPACTUS-8-10 SECTIONS'>ADMIN - STORAGE-COMPACTUS-8-10 SECTIONS</option>
					<option value='ADMIN STORAGE-COMPACTUS-CAROUSEL'>ADMIN - STORAGE-COMPACTUS-CAROUSEL</option>
					<option value='ADMIN STORAGE-CUPBOARD-COAT'>ADMIN - STORAGE-CUPBOARD-COAT</option>
					<option value='ADMIN STORAGE-CUPBOARD-LOWBOY-EXECUTIVE'>ADMIN - STORAGE-CUPBOARD-LOWBOY-EXECUTIVE</option>
					<option value='ADMIN STORAGE-CUPBOARD-LOWBOY-STEEL-SECURITY'>ADMIN - STORAGE-CUPBOARD-LOWBOY-STEEL-SECURITY</option>
					<option value='ADMIN STORAGE-CUPBOARD-LOWBOY-WOOD'>ADMIN - STORAGE-CUPBOARD-LOWBOY-WOOD</option>
					<option value='ADMIN STORAGE-CUPBOARD-TALLBOY-STEEL-SECURITY'>ADMIN - STORAGE-CUPBOARD-TALLBOY-STEEL-SECURITY</option>
					<option value='ADMIN STORAGE-CUPBOARD-TALLBOY-WOOD'>ADMIN - STORAGE-CUPBOARD-TALLBOY-WOOD</option>
					<option value='ADMIN STORAGE-CUPBOARD LOWBOY ROLLER DOOR'>ADMIN - STORAGE-CUPBOARD LOWBOY ROLLER DOOR</option>
					<option value='ADMIN STORAGE-CUPBOARD TALLBOY ROLLER DOOR'>ADMIN - STORAGE-CUPBOARD TALLBOY ROLLER DOOR</option>
					<option value='ADMIN STORAGE-DISPLAY CABINET'>ADMIN - STORAGE-DISPLAY CABINET</option>
					<option value='ADMIN STORAGE-FILING CABINET-LATERAL-4-5 DRAWER'>ADMIN - STORAGE-FILING CABINET-LATERAL-4-5 DRAWER</option>
					<option value='ADMIN STORAGE-FILING CABINET 2-3 DRAWER-EXECUTIVE'>ADMIN - STORAGE-FILING CABINET 2-3 DRAWER-EXECUTIVE</option>
					<option value='ADMIN STORAGE-FILING CABINET 4-5 DRAWER-STEEL'>ADMIN - STORAGE-FILING CABINET 4-5 DRAWER-STEEL</option>
					<option value='ADMIN STORAGE-FILING CABINET 5+ DRAWER-LATERAL'>ADMIN - STORAGE-FILING CABINET 5+ DRAWER-LATERAL</option>
					<option value='ADMIN STORAGE-FLAMMABLE STORAGE-SHIPPING CONTAINER'>ADMIN - STORAGE-FLAMMABLE STORAGE-SHIPPING CONTAINER</option>
					<option value='ADMIN STORAGE-KEY CABINET'>ADMIN - STORAGE-KEY CABINET</option>
					<option value='ADMIN STORAGE-LATERAL FILING UNIT-MOBILE'>ADMIN - STORAGE-LATERAL FILING UNIT-MOBILE</option>
					<option value='ADMIN STORAGE-LOCKER-FLAMMABLE-TALLBOY'>ADMIN - STORAGE-LOCKER-FLAMMABLE-TALLBOY</option>
					<option value='ADMIN STORAGE-LOCKER-SECTIONAL'>ADMIN - STORAGE-LOCKER-SECTIONAL</option>
					<option value='ADMIN STORAGE-LOCKER-SINGLE DOOR'>ADMIN - STORAGE-LOCKER-SINGLE DOOR</option>
					<option value='ADMIN STORAGE-MAGAZINE STAND'>ADMIN - STORAGE-MAGAZINE STAND</option>
					<option value='ADMIN STORAGE-MAP CABINET-VERTICAL'>ADMIN - STORAGE-MAP CABINET-VERTICAL</option>
					<option value='ADMIN STORAGE-MAP DRAWERS'>ADMIN - STORAGE-MAP DRAWERS</option>
					<option value='ADMIN STORAGE-MOBILE PEDESTAL'>ADMIN - STORAGE-MOBILE PEDESTAL</option>
					<option value='ADMIN STORAGE-PIGEON HOLES'>ADMIN - STORAGE-PIGEON HOLES</option>
					<option value='ADMIN STORAGE-SAFE-2-3 DRAWER B CLASS'>ADMIN - STORAGE-SAFE-2-3 DRAWER B CLASS</option>
					<option value='ADMIN STORAGE-SAFE-2-3 DRAWER C CLASS'>ADMIN - STORAGE-SAFE-2-3 DRAWER C CLASS</option>
					<option value='ADMIN STORAGE-SAFE-4 DRAWER B CLASS'>ADMIN - STORAGE-SAFE-4 DRAWER B CLASS</option>
					<option value='ADMIN STORAGE-SAFE-4 DRAWER C CLASS'>ADMIN - STORAGE-SAFE-4 DRAWER C CLASS</option>
					<option value='ADMIN STORAGE-SAFE-COMBINATION AND/OR KEY-LARGE'>ADMIN - STORAGE-SAFE-COMBINATION AND/OR KEY-LARGE</option>
					<option value='ADMIN STORAGE-SAFE-DIGITAL COMBINATION SAFE-SMALL'>ADMIN - STORAGE-SAFE-DIGITAL COMBINATION SAFE-SMALL</option>
					<option value='ADMIN STORAGE-SAFE-PETTY CASH SAFE-SMALL'>ADMIN - STORAGE-SAFE-PETTY CASH SAFE-SMALL</option>
					<option value='ADMIN STORAGE-SHELVING UNIT-CLOTHING'>ADMIN - STORAGE-SHELVING UNIT-CLOTHING</option>
					<option value='ADMIN STORAGE-SHELVING UNIT-COOL ROOM'>ADMIN - STORAGE-SHELVING UNIT-COOL ROOM</option>
					<option value='ADMIN STORAGE-SHELVING UNIT-PALLET RACKING'>ADMIN - STORAGE-SHELVING UNIT-PALLET RACKING</option>
					<option value='ADMIN STORAGE-SHELVING UNIT-STAINLESS'>ADMIN - STORAGE-SHELVING UNIT-STAINLESS</option>
					<option value='ADMIN STORAGE-SHELVING UNIT-STATIONERY'>ADMIN - STORAGE-SHELVING UNIT-STATIONERY</option>
					<option value='ADMIN STORAGE-WRAPPING MACHINE'>ADMIN - STORAGE-WRAPPING MACHINE</option>
					<option value='ADMIN SWIMMING POOL EQUIPMENT-FIRST AID BENCH'>ADMIN - SWIMMING POOL EQUIPMENT-FIRST AID BENCH</option>
					<option value='ADMIN SWIMMING POOL EQUIPMENT-LANE ROPE STORAGE REEL'>ADMIN - SWIMMING POOL EQUIPMENT-LANE ROPE STORAGE REEL</option>
					<option value='ADMIN SWIMMING POOL EQUIPMENT-LANE ROPES (25M SET OF)'>ADMIN - SWIMMING POOL EQUIPMENT-LANE ROPES (25M SET OF)</option>
					<option value='ADMIN SWIMMING POOL EQUIPMENT-OUTDOOR FURNITURE'>ADMIN - SWIMMING POOL EQUIPMENT-OUTDOOR FURNITURE</option>
					<option value='ADMIN SWIMMING POOL EQUIPMENT-POOL CLEANER'>ADMIN - SWIMMING POOL EQUIPMENT-POOL CLEANER</option>
					<option value='ADMIN SWIMMING POOL EQUIPMENT-POOL COVER'>ADMIN - SWIMMING POOL EQUIPMENT-POOL COVER</option>
					<option value='ADMIN SWIMMING POOL EQUIPMENT-SAIL SHADE'>ADMIN - SWIMMING POOL EQUIPMENT-SAIL SHADE</option>
					<option value='ADMIN TABLE-BEDSIDE'>ADMIN - TABLE-BEDSIDE</option>
					<option value='ADMIN TABLE-BAR'>ADMIN - TABLE-BAR</option>
					<option value='ADMIN TABLE-BOARDROOM-TIMBER'>ADMIN - TABLE-BOARDROOM-TIMBER</option>
					<option value='ADMIN TABLE-BOARDROOM-VENEER'>ADMIN - TABLE-BOARDROOM-VENEER</option>
					<option value='ADMIN TABLE-COFFEE-LAMINATE'>ADMIN - TABLE-COFFEE-LAMINATE</option>
					<option value='ADMIN TABLE-COFFEE-TIMBER'>ADMIN - TABLE-COFFEE-TIMBER</option>
					<option value='ADMIN TABLE-COFFEE-VENEER'>ADMIN - TABLE-COFFEE-VENEER</option>
					<option value='ADMIN TABLE-CONFERENCE-TIMBER'>ADMIN - TABLE-CONFERENCE-TIMBER</option>
					<option value='ADMIN CONFERENCE-VENEER'>ADMIN - CONFERENCE-VENEER</option>
					<option value='ADMIN TABLE-DINING'>ADMIN - TABLE-DINING</option>
					<option value='ADMIN TABLE-FOLDING FUNCTION'>ADMIN - TABLE-FOLDING FUNCTION</option>
					<option value='ADMIN TABLE-GENERAL'>ADMIN - TABLE-GENERAL</option>
					<option value='ADMIN TABLE-LIGHT TABLE'>ADMIN - TABLE-LIGHT TABLE</option>
					<option value='ADMIN TABLE-MEETING-LAMINATE'>ADMIN - TABLE-MEETING-LAMINATE</option>
					<option value='ADMIN TABLE-MEETING-TIMBER'>ADMIN - TABLE-MEETING-TIMBER</option>
					<option value='ADMIN TABLE-MEETING-VENEER'>ADMIN - TABLE-MEETING-VENEER</option>
					<option value='ADMIN TABLE-OUTDOOR-PLASTIC'>ADMIN - TABLE-OUTDOOR-PLASTIC</option>
					<option value='ADMIN TABLE-OUTDOOR-WOOD'>ADMIN - TABLE-OUTDOOR-WOOD</option>
					<option value='ADMIN TABLE-PICNIC'>ADMIN - TABLE-PICNIC</option>
					<option value='ADMIN TABLE-RECEPTION DESK-LAMINATE'>ADMIN - TABLE-RECEPTION DESK-LAMINATE</option>
					<option value='ADMIN TABLE DRAFTING'>ADMIN - TABLE DRAFTING</option>
					<option value='ADMIN THEATRE EQUIPMENT-CINEMA-PROJECTOR'>ADMIN - THEATRE EQUIPMENT-CINEMA-PROJECTOR</option>
					<option value='ADMIN THEATRE EQUIPMENT-CINEMA-SOUND SYSTEM'>ADMIN - THEATRE EQUIPMENT-CINEMA-SOUND SYSTEM</option>
					<option value='ADMIN THEATRE EQUIPMENT-PROJECTOR-FILM'>ADMIN - THEATRE EQUIPMENT-PROJECTOR-FILM</option>
					<option value='ADMIN THEATRE EQUIPMENT-SCREEN-AUTOMATIC'>ADMIN - THEATRE EQUIPMENT-SCREEN-AUTOMATIC</option>
					<option value='ADMIN THEATRE EQUIPMENT-SCREEN-CONCAVE'>ADMIN - THEATRE EQUIPMENT-SCREEN-CONCAVE</option>
					<option value='ADMIN THEATRE EQUIPMENT-SCREEN-FREE STANDING'>ADMIN - THEATRE EQUIPMENT-SCREEN-FREE STANDING</option>
					<option value='ADMIN THEATRE EQUIPMENT-SCREEN-PROJECTION'>ADMIN - THEATRE EQUIPMENT-SCREEN-PROJECTION</option>
					<option value='ADMIN THEATRE EQUIPMENT-SCREEN-WALL/CEILING MOUNTED'>ADMIN - THEATRE EQUIPMENT-SCREEN-WALL/CEILING MOUNTED</option>
					<option value='ADMIN TRAILER-DUAL AXLE'>ADMIN - TRAILER-DUAL AXLE</option>
					<option value='ADMIN TRAILER-SINGLE AXLE'>ADMIN - TRAILER-SINGLE AXLE</option>
					<option value='ADMIN TROLLEY-AUDIO VISUAL'>ADMIN - TROLLEY-AUDIO VISUAL</option>
					<option value='ADMIN TROLLEY-BAKERS'>ADMIN - TROLLEY-BAKERS</option>
					<option value='ADMIN TROLLEY-FLAT BED'>ADMIN - TROLLEY-FLAT BED</option>
					<option value='ADMIN TROLLEY-FOOD-PLASTIC'>ADMIN - TROLLEY-FOOD-PLASTIC</option>
					<option value='ADMIN TROLLEY-FOOD-S/STEEL'>ADMIN - TROLLEY-FOOD-S/STEEL</option>
					<option value='ADMIN TROLLEY-HOT BOX'>ADMIN - TROLLEY-HOT BOX</option>
					<option value='ADMIN TROLLEY-HYDRAULIC'>ADMIN - TROLLEY-HYDRAULIC</option>
					<option value='ADMIN TROLLEY-PLATE'>ADMIN - TROLLEY-PLATE</option>
					<option value='ADMIN TROLLEY-STAIR CLIMBING TROLLEY'>ADMIN - TROLLEY-STAIR CLIMBING TROLLEY</option>
					<option value='ADMIN TROLLEY-UTENSIL'>ADMIN - TROLLEY-UTENSIL</option>
					<option value='ADMIN WHARF EQUIPMENT-FLAT-TOP LIGHTER'>ADMIN - WHARF EQUIPMENT-FLAT-TOP LIGHTER</option>
					<option value='ADMIN WHARF EQUIPMENT-NAVIGATIONAL AIDS'>ADMIN - WHARF EQUIPMENT-NAVIGATIONAL AIDS</option>
					<option value='ADMIN WHARF EQUIPMENT-OIL SPILL EQUIPMENT'>ADMIN - WHARF EQUIPMENT-OIL SPILL EQUIPMENT</option>
					<option value='ADMIN WHARF EQUIPMENT-SMALL BOAT EQUIPMENT'>ADMIN - WHARF EQUIPMENT-SMALL BOAT EQUIPMENT</option>
					<option value='ADMIN WHITEBOARD-FLIPCHART'>ADMIN - WHITEBOARD-FLIPCHART</option>
					<option value='ADMIN WHITEBOARD ELECTRONIC-FREESTANDING'>ADMIN - WHITEBOARD ELECTRONIC-FREESTANDING</option>
					<option value='ADMIN WHITEBOARD ELECTRONIC-WALL MOUNTED'>ADMIN - WHITEBOARD ELECTRONIC-WALL MOUNTED</option>
					<option value='ADMIN WHITEBOARD/NOTICEBOARD-FREESTANDING'>ADMIN - WHITEBOARD/NOTICEBOARD-FREESTANDING</option>
					<option value='ADMIN WORKSTATION-EXECUTIVE'>ADMIN - WORKSTATION-EXECUTIVE</option>
					<option value='ADMIN WORKSTATION-ANY SHAPE'>ADMIN - WORKSTATION-ANY SHAPE</option>
					<option value='IT ANTENNA-UNKNOWN'>IT - ANTENNA-UNKNOWN</option>
					<option value='IT CABINET-CLASS B'>IT - CABINET-CLASS B</option>
					<option value='IT CABINET-CLASS C'>IT - CABINET-CLASS C</option>
					<option value='IT CABINET-OTHER'>IT - CABINET-OTHER</option>
					<option value='IT CD TOWER/JUKEBOX'>IT - CD TOWER/JUKEBOX</option>
					<option value='IT CHASSIS-MUX'>IT - CHASSIS-MUX</option>
					<option value='IT CHASSIS-MUX-POWER SUPPLY'>IT - CHASSIS-MUX-POWER SUPPLY</option>
					<option value='IT CHASSIS-MUX-MODULE/BLADE'>IT - CHASSIS-MUX-MODULE/BLADE</option>
					<option value='IT CHASSIS-ROUTER'>IT - CHASSIS-ROUTER</option>
					<option value='IT CHASSIS-ROUTER-POWER SUPPLY'>IT - CHASSIS-ROUTER-POWER SUPPLY</option>
					<option value='IT CHASSIS-ROUTER-MODULE/BLADE'>IT - CHASSIS-ROUTER-MODULE/BLADE</option>
					<option value='IT CHASSIS-SWITCH'>IT - CHASSIS-SWITCH</option>
					<option value='IT CHASSIS-SWITCH-POWER SUPPLY'>IT - CHASSIS-SWITCH-POWER SUPPLY</option>
					<option value='IT CHASSIS-SWITCH-MODULE/BLADE'>IT - CHASSIS-SWITCH-MODULE/BLADE</option>
					<option value='IT COMPUTER-DESKTOP'>IT - COMPUTER-DESKTOP</option>
					<option value='IT COMPUTER-NOTEBOOK/LAPTOP'>IT - COMPUTER-NOTEBOOK/LAPTOP</option>
					<option value='IT DPN SWITCH'>IT - DPN SWITCH</option>
					<option value='IT FIREWALL-HARDWARE'>IT - FIREWALL-HARDWARE</option>
					<option value='IT HUB'>IT - HUB</option>
					<option value='IT INTEGRATED KEYBOARD/MOUSE MONITOR'>IT - INTEGRATED KEYBOARD/MOUSE MONITOR</option>
					<option value='IT MCS SWITCH-TENIX INTERACTIVE LINK'>IT - MCS SWITCH-TENIX INTERACTIVE LINK</option>
					<option value='IT MODEM'>IT - MODEM</option>
					<option value='IT MONITOR CRT-ALL SIZES'>IT - MONITOR CRT-ALL SIZES</option>
					<option value='IT MONITOR-LCD/FLAT PANEL'>IT - MONITOR-LCD/FLAT PANEL</option>
					<option value='IT MONITOR-PLASMA'>IT - MONITOR-PLASMA</option>
					<option value='IT OTHER-MEDIA CONVERTER'>IT - OTHER-MEDIA CONVERTER</option>
					<option value='IT OTHER-GRAPHIC TABLET'>IT - OTHER-GRAPHIC TABLET</option>
					<option value='IT OTHER-EXTERNAL TAPE DRIVE'>IT - OTHER-EXTERNAL TAPE DRIVE</option>
					<option value='IT OTHER-EXTERNAL ZIP DRIVE'>IT - OTHER-EXTERNAL ZIP DRIVE</option>
					<option value='IT OTHER-PRINT SERVER DEVICE'>IT - OTHER-PRINT SERVER DEVICE</option>
					<option value='IT OTHER-SCANNER-DOC FEEDER'>IT - OTHER-SCANNER-DOC FEEDER</option>
					<option value='IT OTHER-SCANNER-HANDHELD'>IT - OTHER-SCANNER-HANDHELD</option>
					<option value='IT OTHER SCANNER-TRANS ADAPTER'>IT - OTHER SCANNER-TRANS ADAPTER</option>
					<option value='IT PDA-GENERIC PDA'>IT - PDA-GENERIC PDA</option>
					<option value='IT PDA-BLACKBERRY'>IT - PDA-BLACKBERRY</option>
					<option value='IT PLOTTER-COLOUR'>IT - PLOTTER-COLOUR</option>
					<option value='IT PLOTTER-GRAPHICS'>IT - PLOTTER-GRAPHICS</option>
					<option value='IT PLOTTER-THERMAL'>IT - PLOTTER-THERMAL</option>
					<option value='IT PRINTER-A3-DOT MATRIX B&W'>IT - PRINTER-A3-DOT MATRIX B&W</option>
					<option value='IT PRINTER-A3-DOT MATRIX COLOUR'>IT - PRINTER-A3-DOT MATRIX COLOUR</option>
					<option value='IT PRINTER-A3-INK JET B&W'>IT - PRINTER-A3-INK JET B&W</option>
					<option value='IT PRINTER-A3-INK JET COLOUR'>IT - PRINTER-A3-INK JET COLOUR</option>
					<option value='IT PRINTER-A3-LASER B&W'>IT - PRINTER-A3-LASER B&W</option>
					<option value='IT PRINTER-A3-LASER COLOUR'>IT - PRINTER-A3-LASER COLOUR</option>
					<option value='IT PRINTER-A4-DOT MATRIX B&W'>IT - PRINTER-A4-DOT MATRIX B&W</option>
					<option value='IT PRINTER-A4-DOT MATRIX COLOUR'>IT - PRINTER-A4-DOT MATRIX COLOUR</option>
					<option value='IT PRINTER-A4-INK JET B&W'>IT - PRINTER-A4-INK JET B&W</option>
					<option value='IT PRINTER-A4-INK JET COLOUR'>IT - PRINTER-A4-INK JET COLOUR</option>
					<option value='IT PRINTER-A4-LASER B&W'>IT - PRINTER-A4-LASER B&W</option>
					<option value='IT PRINTER-A4-LASER COLOUR'>IT - PRINTER-A4-LASER COLOUR</option>
					<option value='IT PRINTER-OTHER-BRAILLE'>IT - PRINTER-OTHER-BRAILLE</option>
					<option value='IT PRINTER-OTHER-LABEL'>IT - PRINTER-OTHER-LABEL</option>
					<option value='IT PRINTER-OTHER-THERMAL'>IT - PRINTER-OTHER-THERMAL</option>
					<option value='IT PRINTER-OTHER-MULTIFUNCTION'>IT - PRINTER-OTHER-MULTIFUNCTION</option>
					<option value='IT SCANNER-FILM'>IT - SCANNER-FILM</option>
					<option value='IT SCANNER-FLATBED'>IT - SCANNER-FLATBED</option>
					<option value='IT SERVER-FILE'>IT - SERVER-FILE</option>
					<option value='IT SERVER-SAN/STORAGE'>IT - SERVER-SAN/STORAGE</option>
					<option value='IT SERVER-TERMINAL'>IT - SERVER-TERMINAL</option>
					<option value='IT SERVER-VIDEO'>IT - SERVER-VIDEO</option>
					<option value='IT STANDALONE-MUX-POWER SUPPLY'>IT - STANDALONE-MUX-POWER SUPPLY</option>
					<option value='IT STANDALONE-MUX'>IT - STANDALONE-MUX</option>
					<option value='IT STANDALONE-ROUTER-POWER SUPPLY'>IT - STANDALONE-ROUTER-POWER SUPPLY</option>
					<option value='IT STANDALONE-ROUTER-MODULE/BLADE'>IT - STANDALONE-ROUTER-MODULE/BLADE</option>
					<option value='IT STANDALONE-ROUTER'>IT - STANDALONE-ROUTER</option>
					<option value='IT STANDALONE-SWITCH-POWER SUPPLY'>IT - STANDALONE-SWITCH-POWER SUPPLY</option>
					<option value='IT STANDALONE-SWITCH-MODULE/BLADE'>IT - STANDALONE-SWITCH-MODULE/BLADE</option>
					<option value='IT STANDALONE-SWITCH'>IT - STANDALONE-SWITCH</option>
					<option value='IT TAPE LIBRARY'>IT - TAPE LIBRARY</option>
					<option value='IT TERMINAL-DUMB'>IT - TERMINAL-DUMB</option>
					<option value='IT TERMINAL-OTHER'>IT - TERMINAL-OTHER</option>
					<option value='IT TERMINAL ADAPTER'>IT - TERMINAL ADAPTER</option>
					<option value='IT BATTERY PACK'>IT - BATTERY PACK</option>
					<option value='IT CONTROLLER'>IT - CONTROLLER</option>
					<option value='IT LINE CONDITIONER'>IT - LINE CONDITIONER</option>
					<option value='IT STANDALONE UPS'>IT - STANDALONE UPS</option>
					<option value='IT WIRELESS HARWARE'>IT - WIRELESS HARWARE</option>

		    	</select>
		    </div>
		    <div class="col-1"></div>
		</div>

		<div class="row">
		    <div class="col-1"></div>
		    <div class="col-lg">
		    	<b>3. How was the first found created?</b>
		    </div>
		    <div class="col-1"></div>
		</div>
		<div class="row">
		    <div class="col-lg">
				<table width="100%" class="table">
					<?=$row_firstfound?>
				</table>
		    </div>


		</div>

	</div>
</form>






<?php include "04_footer.php"; ?>